# Site settings
name: Thomas "TJ" Wolschon
email: tjw3948@rit.edu
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Game Developer, C#, Unity, C++, JavaScript"
skills: "Student / Lead Game Developer and CTO at Ardin Interactive"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/thomas-wolschon-248134127/
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: A097C2
  primary-rgb: "160, 151, 194"
  secondary: 31313C
  secondary-dark: 69527E
  section-tout: F4F2FC


# Build settings
markdown: kramdown
permalink: pretty
